services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: flowpay
      POSTGRES_USER: flowpay
      POSTGRES_PASSWORD: flowpay
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  db_test:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: flowpay_test
      POSTGRES_USER: flowpay
      POSTGRES_PASSWORD: flowpay
    ports:
      - "5433:5432"

volumes:
  postgres_data: