export const theme = {
  colors: {
    background: '#f3f7f6',
    surface: '#ffffff',
    surfaceMuted: '#e7f0ee',
    primary: '#a149ff',
    primaryPressed: '#8333d8',
    primaryTint: '#f1e4ff',
    primaryText: '#ffffff',
    accent: '#a149ff',
    accentTint: '#f1e4ff',
    text: '#102524',
    mutedText: '#60716f',
    border: '#d7e2df',
    danger: '#c2413b',
    dangerPressed: '#9f302c',
    dangerTint: '#fde8e6',
    success: '#138a65',
    successTint: '#dff5ec',
    warning: '#946200',
    warningTint: '#fff2cc',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    xxl: 32,
  },
  radius: {
    sm: 6,
    md: 8,
    lg: 16,
    xl: 24,
  },
  typography: {
    title: 30,
    subtitle: 18,
    body: 16,
    small: 14,
  },
  shadow: {
    card: {
      shadowColor: '#002f36',
      shadowOpacity: 0.08,
      shadowRadius: 14,
      shadowOffset: { width: 0, height: 8 },
      elevation: 2,
    },
  },
} as const
