"""create ledger_transactions table

Revision ID: c87dd4f707cd
Revises: f05f69014b9a
Create Date: 2026-05-14 22:50:44.785398

"""

revision = 'c87dd4f707cd'
down_revision = 'f05f69014b9a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_transactions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('wallet_id', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('operation_id', sa.Text(), nullable=True),
    sa.Column('counterparty_wallet_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(source = 'welcome_bonus' AND operation_id IS NULL) OR (source IN ('manual_transfer', 'nfc_transfer') AND operation_id IS NOT NULL)", name='ck_ledger_transactions_operation_reference'),
    sa.CheckConstraint("(type = 'credit' AND source IN ('welcome_bonus', 'manual_transfer', 'nfc_transfer')) OR (type = 'debit' AND source IN ('manual_transfer', 'nfc_transfer'))", name='ck_ledger_transactions_type_source'),
    sa.CheckConstraint("currency = 'COP'", name='ck_ledger_transactions_currency_cop'),
    sa.CheckConstraint("source IN ('welcome_bonus', 'manual_transfer', 'nfc_transfer')", name='ck_ledger_transactions_source'),
    sa.CheckConstraint("type IN ('credit', 'debit')", name='ck_ledger_transactions_type'),
    sa.CheckConstraint('amount > 0', name='ck_ledger_transactions_amount_positive'),
    sa.ForeignKeyConstraint(['counterparty_wallet_id'], ['wallets.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ledger_transactions_operation_id', 'ledger_transactions', ['operation_id'], unique=False)
    op.create_index('ix_ledger_transactions_wallet_created', 'ledger_transactions', ['wallet_id', 'created_at'], unique=False)
    op.create_index('uq_ledger_transactions_welcome_bonus_wallet', 'ledger_transactions', ['wallet_id'], unique=True, postgresql_where=sa.text("source = 'welcome_bonus'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_ledger_transactions_welcome_bonus_wallet', table_name='ledger_transactions', postgresql_where=sa.text("source = 'welcome_bonus'"))
    op.drop_index('ix_ledger_transactions_wallet_created', table_name='ledger_transactions')
    op.drop_index('ix_ledger_transactions_operation_id', table_name='ledger_transactions')
    op.drop_table('ledger_transactions')
    # ### end Alembic commands ###
