"""create transfer_operations and idempotency_keys

Revision ID: d2aff0e6e0ab
Revises: c87dd4f707cd
Create Date: 2026-05-15 07:28:34.691591

"""

revision = 'd2aff0e6e0ab'
down_revision = 'c87dd4f707cd'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_keys',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('request_hash', sa.Text(), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_idempotency_keys_user_key', 'idempotency_keys', ['user_id', 'key'], unique=True)
    op.create_table('transfer_operations',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('source_wallet_id', sa.Text(), nullable=False),
    sa.Column('destination_wallet_id', sa.Text(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("currency = 'COP'", name='ck_transfer_operations_currency_cop'),
    sa.CheckConstraint("origin IN ('manual_transfer', 'nfc_transfer')", name='ck_transfer_operations_origin'),
    sa.CheckConstraint("status IN ('completed', 'failed')", name='ck_transfer_operations_status'),
    sa.CheckConstraint('amount > 0', name='ck_transfer_operations_amount_positive'),
    sa.CheckConstraint('source_wallet_id <> destination_wallet_id', name='ck_transfer_operations_wallets_differ'),
    sa.ForeignKeyConstraint(['destination_wallet_id'], ['wallets.id'], ),
    sa.ForeignKeyConstraint(['source_wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transfer_operations_created_at', 'transfer_operations', ['created_at'], unique=False)
    op.create_index('ix_transfer_operations_destination_wallet', 'transfer_operations', ['destination_wallet_id'], unique=False)
    op.create_index('ix_transfer_operations_source_wallet', 'transfer_operations', ['source_wallet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transfer_operations_source_wallet', table_name='transfer_operations')
    op.drop_index('ix_transfer_operations_destination_wallet', table_name='transfer_operations')
    op.drop_index('ix_transfer_operations_created_at', table_name='transfer_operations')
    op.drop_table('transfer_operations')
    op.drop_index('uq_idempotency_keys_user_key', table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    # ### end Alembic commands ###
